#!/bin/bash
echo "========== DIAGNOSIS =========="
echo ""
echo "1. POSTGRES LOGS (last 30 lines):"
docker compose logs postgres --tail=30 2>/dev/null || echo "No logs available"
echo ""
echo "2. VOLUME CONFIGURATION:"
grep -A5 "volumes:" docker-compose.yaml | grep -A10 "postgres:"
echo ""
echo "3. DOCKER VOLUMES:"
docker volume ls | grep -E "(personal|postgres)"
echo ""
echo "4. DATA DIRECTORY PERMISSIONS:"
ls -la ./data/postgres/ 2>/dev/null || echo "No data directory"
echo ""
echo "5. .env FILE (first lines):"
head -10 .env 2>/dev/null || echo "No .env file"
echo ""
echo "6. DOCKER PS STATUS:"
docker ps -a | grep postgres
echo ""
echo "========== END =========="
