# Security
ssl = on
ssl_cert_file = '/etc/ssl/certs/ssl-cert-snakeoil.pem'
ssl_key_file = '/etc/ssl/private/ssl-cert-snakeoil.key'
password_encryption = scram-sha-256

# Performance
max_connections = 100
shared_buffers = 256MB
work_mem = 8MB

# Replication (для HA)
wal_level = replica
max_wal_senders = 8
hot_standby = on
ssl = on
